### ISSUE TITLE
Open Cover UI plugin isn't compatible with VS 2015 Community Edition

### ISSUE THREAD

**Issue by animeshb** [OpenCoverUI/OpenCover.UI#85] opened 2015-07-25 12:10 UTC
I get the following error when I try to install in Visual Studio 2015 Community Edition on Windows 8.1.

<img width="343" alt="capture" src="https://cloud.githubusercontent.com/assets/1550696/8889349/1a7318c4-32f4-11e5-8c08-1ee31ca5dc89.PNG">

Error log:
	7/25/2015 5:36:50 PM - Searching for applicable products...
	7/25/2015 5:36:50 PM - Found installed product - Microsoft Visual Studio Community 2015
	7/25/2015 5:36:50 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
	7/25/2015 5:36:50 PM - Found installed product - Global Location
	7/25/2015 5:36:50 PM - Found installed product - ssms
	7/25/2015 5:36:50 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
	   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
	   at VSIXInstaller.App.InitializeInstall()
	   at System.Threading.Tasks.Task.InnerInvoke()
	   at System.Threading.Tasks.Task.Execute()

**Comment by pver** [comment] 2015-07-25 15:47
The plugin only supports VS 2012 and 2013 at this moment, but I'll add VS 2015 support in the coming days.

That will be a good point to make a new release with the issues we fixed so far.

**Comment by sawilde** [comment] 2015-07-26 07:27
:+1:

**Comment by pver** [comment] 2015-07-29 21:43
@animeshb did you experience this on a machine that only has VS2015 installed? If so, would you be so kind to test a snapshot with the fix I made in #87 ? The snapshot installer can be found on the appveyor artifact page: https://ci.appveyor.com/project/sawilde/opencover-ui/build/1.0.76/artifacts

I successfully tested the fix on:
- a machine with only VS2012 installed
- a machine with VS2013 and VS2015 installed
but I don't have a machine with only VS2015 at the moment, and I want to be sure it successfully installs on a VS2015-only environment before closing the issue.

For future regression tests, I'll create 3 separate virtual machines with VS2012, VS2013 or VS2015 installed in it

**Comment by pver** [comment] 2015-07-29 21:44
We'll also need to fix some of the references used in the project. Because at the moment, a build can only be installed in a Visual Studio version higher or equal to the one used for building:
- when building from VS2012: it installs on VS2012-only and VS2013-only and VS2013 with VS2015 machines
- when building from VS2013: it installs on VS2013-only and VS2013 with VS2015 => it does not install on a VS2012-only build because some reference to a VS2013 version of the visual studio sdk slips into the build
I studied the approach used in other plugins and have some steps we can take to fix this, but I'll create a separate issue to further handle this as it's not related to this specific issue (and we always build the finale releases from VS2012 at the moment anyway)

**Comment by pver** [comment] 2015-07-29 21:47
Forgot to mention: I tested this with installing the plugin in VS2015 Community Edition, but other versions should be supported as well with this fix

**Comment by animeshb** [comment] 2015-07-29 23:46
Peter, thanks for the update. Now, I have only Visual Studio 2015 installed. I will test and get back to you in a few.

**Comment by animeshb** [comment] 2015-07-30 00:10
Thanks, I was able to install it now. Please close the issue.

**Comment by pver** [comment] 2015-07-30 06:24
Great to hear, thanks for testing it!

**Closed** 2015-07-30 06:25 UTC
Labels: VSIX
