### ISSUE TITLE
Coverage results not showing coverage for my tests, but for other .dlls

### ISSUE THREAD

**Issue by Boohy** [OpenCoverUI/OpenCover.UI#101] opened 2015-12-23 07:46 UTC
I am using VS 2015 professional, and I wanted to see the code coverage for my project.
I was following this guide:
https://visualstudiogallery.msdn.microsoft.com/6950a046-8919-4935-8542-c6f37956f688
Everything is fine except Step 3. It doesn't show my classes and methods, but some other .dlls. Screenshot:
![GitHub Logo](http://i.stack.imgur.com/BiSCP.jpg)
Any suggestions why it is not showing code coverage for my methods?
Thanks

**Comment by pver** [comment] 2015-12-23 11:17
This might be caused by one of the open issues: do you have TestFixture attributes on your classes? These are no longer required by nunit, but the discoverer in opencover.ui still requires them while discovering tests (even if a base class already has the attribute).

**Comment by Boohy** [comment] 2015-12-23 11:45
Hi,
thanks for the fast reply.
I am using MSTest with [TestClass] and [TestMethod] attributes on classses/methods.
Tests are being discovered and run in OpenCover Test Explorer without any problems, the only thing that is not working as it should is the code coverage results.

**Comment by pver** [comment] 2015-12-24 17:08
I'll see if I can reproduce this with MSTest. Do you notice any errors or warnings in the opencover.ui output window? It's located in the Visual Studio Output window that also show build output (it should have an opencover.ui item in the combobox).

**Comment by Boohy** [comment] 2015-12-25 11:12
I will take a look on output window on Monday morning, when I will be at work computer and let you know.

**Comment by Boohy** [comment] 2015-12-28 07:20
Nothing unusual in the output window, just statistics about run/failed tests etc.

**Comment by HarelM** [comment] 2016-02-03 22:56
Same here, two dlls are showing:
using mstest.
I'm trying to migrate from open cover Nuget + Report Generator + batch file to this UI.
I don't have any config file in my root solution folder (I assume the defaults should work out of the box?)
![image](https://cloud.githubusercontent.com/assets/3269297/12799824/c4b1f936-cad9-11e5-841c-7c4cafc6b18e.png)

**Comment by pver** [comment] 2016-02-04 10:23
I couldn't reproduce it myself so far :(

Do you use specific project settings, for instance mixed .net framework versions or mixed target platforms (x64 vs x86 vs Any)?
Can you extract a small example project that produces the issue?

**Comment by HarelM** [comment] 2016-02-04 18:19
I'm using the defaults - .Net 4.5 Any CPU, I didn't find any difference between the DAL and the DALInterfaces properties.
The problem was I installed an old version from a branch and not the released from the main repository, sorry for the false alarm.
Coverage is as expected.

**Comment by pver** [comment] 2016-02-04 18:28
Glad to hear it's working now :+1: 

@Boohy did you test this with the latest release?

**Comment by HarelM** [comment] 2016-02-04 18:55
I know what caused this: In visual studio gallery the link is to here:
https://github.com/sawilde/opencover/releases
which made me install a bad version...
Please fix the link described here:
https://visualstudiogallery.msdn.microsoft.com/6950a046-8919-4935-8542-c6f37956f688

**Comment by pver** [comment] 2016-02-04 18:57
Oh, I see, thanks for the info! 

@jamdagni86 can you update the link on visualstudiogallery?

**Comment by jamdagni86** [comment] 2016-02-07 08:41
Done. Now, it's pointing to - https://github.com/opencover/opencover/releases.

**Comment by pver** [comment] 2016-02-07 18:17
Great, thanks! :+1: 

I think we can close this one for now. @Boohy if the issue remains after upgrading to the new opencover release, feel free to reopen this ticket

**Closed by pver** 2016-02-07 18:17 UTC
Labels: bug, MSTest
